### ISSUE TITLE
TypeError: Cannot read property 'shortenPath' of undefined

### ISSUE THREAD

**Issue by rishu605** [react-loadable/revised#3] opened 2022-11-16 06:16 UTC
I recently moved from react-loadable to @react-loadable/revised.

Currently we are using Babel 6.26 in our project. Revised React-loadable has a dependency of babel ^7.

I get the following error on running npm run build. Could this be an issue due to babel 6 not working with this plugin ?
![Screenshot from 2022-11-16 10-17-10](https://user-images.githubusercontent.com/16971746/202099100-5cc489b3-0828-400f-a1a3-69ea7cae5855.png)

**Comment by tranvansang** [comment] 2022-11-17 08:31
@rishu605 

can you try updating the package v1.3.2?

**Comment by rishu605** [comment] 2022-11-17 09:16
Hey @tranvansang ,
Thanks for this. Updating resolved the above issue.
But, I have been getting another issue as well. This occurred with v1.3.1 as well.
```
ERROR in ENOENT: no such file or directory, open '/opt/maatran/build/react-loadable.json'
Error: ENOENT: no such file or directory, open '/opt/maatran/build/react-loadable.json'

ERROR in ENOENT: no such file or directory, open '/opt/maatran/build/react-loadable.json'
Error: ENOENT: no such file or directory, open '/opt/maatran/build/react-loadable.json'`
```

my webpack file has following implementation of ReactloadablePlugin:

```
import { ReactLoadablePlugin } from '@react-loadable/revised/webpack';
const fs = require('fs')
const fsPromises = fs.promises

const plugins = [
  // some plugins here
  new ReactLoadablePlugin({
    async callback(manifest) {
      await fsPromises.writeFile(
        path.resolve(process.cwd(), 'build/react-loadable.json'),
        JSON.stringify(manifest, null, 2),
        {
          encoding: "utf8",
          flag: "w+"
        }
      )
    },
    absPath: true
  }),
// some other plugins here
]
```

in .babelrc, I have this included in "plugins" -- "@react-loadable/revised/babel"

All my Loadable files have been updated as follows:
```
import loadable from '@react-loadable/revised'

export default loadable({
  loader: () =>
    import(/* webpackChunkName: "HomePage" */ 'containers/HomePage'),
  modules: ['containers/HomePage'],
  loading: () => null,
});
```

I changed other imports as well according to the docs.

**Comment by tranvansang** [comment] 2022-11-17 10:13
I think the problem is this line 

```
        path.resolve(process.cwd(), 'build/react-loadable.json'),
```

When webpack compiles, the `callback` is called with an object as the only parameter (`manifest`). Inside this callback, you need to store the manifest somewhere to be used later in the backend.

**Comment by tranvansang** [comment] 2022-11-17 10:15
you can console.log the resolved path (the result by `path.resolve` call) , and check if the manifest is exported properly before going to the next step.

**Comment by tranvansang** [comment] 2022-11-17 10:20
One more thing,

```
  modules: ['containers/HomePage'],
```

you do not need this line. It will be inserted automatically by the babel plugin. The docs is currently confusing. I will update it.

**Comment by rishu605** [comment] 2022-11-17 10:33
> I think the problem is this line
> 
> ```
>         path.resolve(process.cwd(), 'build/react-loadable.json'),
> ```
> 
> When webpack compiles, the `callback` is called with an object as the only parameter (`manifest`). Inside this callback, you need to store the manifest somewhere to be used later in the backend.

I didn't quite get what exactly we need to do with the manifest object passed into the callback.
Added following console.log just inside the callback()
This seems to be returning proper values
```
console.log('PATH.JOIN: ', path.resolve(process.cwd(), 'build/react-loadable.json'))
console.log('MANIFEST: ', manifest)
```
Getting following on the console.
![Screenshot from 2022-11-17 16-01-41](https://user-images.githubusercontent.com/16971746/202423376-3227b606-e2bc-456c-85fb-61b3601a93d2.png)


Regarding the modules thing. Got it! I saw that in the docs.

**Comment by tranvansang** [comment] 2022-11-17 10:46
then try 'cat /opt/maatran/build/react-loadable.json' and check if react-loadable.json is saved properly after the build.

**Comment by rishu605** [comment] 2022-11-17 10:52
Seems like, react-loadable.json is not getting created.

**Comment by tranvansang** [comment] 2022-11-17 10:54
Yes. The plugin does not decide where to store the manifest object. You need to find a proper place to store it (into the hard disk)

**Comment by rishu605** [comment] 2022-11-17 11:01
Oh!
So that means, (If I'm understanding it correctly) the webpack's manifest object that is passed into the callback, I need to store it (in hard disk) and then when we use it in the ```JSON.stringify(manifest, null,2)``` call, I need to first get the manifest from my hard disk, then pass that manifest object into this JSON.stringify call.

The manifest passed into the callback does not work properly when used directly by the JSON.stringify call. Is this the case ?

**Comment by tranvansang** [comment] 2022-11-17 11:05
> I need to store it (in hard disk)

Yes. But it is an object, you must stringify it before saving to the plain text format.

>  and then when we use it in the JSON.stringify(manifest, null,2) call, I need to first get the manifest from my hard disk, then pass that manifest object into this JSON.stringify call.

No

> The manifest passed into the callback does not work properly when used directly by the JSON.stringify call. Is this the case ?
> by the JSON.stringify call

I do not think there is any problem with JSON.stringify. The problem is your chosen path is in `/opt/...` directory. That maybe cause permission issue. You need to choose other path, better to choose a build directory in your project.

There is no need to read any file from hard disk in this callback.

**Comment by rishu605** [comment] 2022-11-17 11:17
Oh okay!

Can you help with what the code should look like inside the callback. I got the part that it's not necessary to store any thing in a file.

I changed the callback() to look something like this:
```
new ReactLoadablePlugin({
      async callback(manifest) {
        console.log('PATH.JOIN: ', path.resolve(process.cwd(), 'build/react-loadable.json'))
        console.log('MANIFEST: ', manifest)
        const mani = JSON.stringify(manifest)
        await fsPromises.writeFile(
          path.join(process.cwd(), '/build/react-loadable.json'),
          JSON.stringify(JSON.parse(mani), null, 2),
          {
            encoding: "utf8",
            flag: "w+"
          }
        )
      },
      absPath: true
    }),
```



> The problem is your chosen path is in `/opt/...` directory. That maybe cause permission issue. You need to choose other path, better to choose a build directory in your project.

Permission is not an issue. Have all the required permissions set. /opt/maatran is the root directory only.

**Comment by tranvansang** [comment] 2022-11-17 11:32
> Permission is not an issue. Have all the required permissions set. /opt/maatran is the root directory only.

the build directory needs to be created first.

**Comment by rishu605** [comment] 2022-11-17 11:48
build directory is getting created. all chunks that are created are getting stored there.

I also use other plugins -- WebpackAssetsManifest, MiniCSSExtractPlugin and others.
WebpackAssets Manifest creates the build directory.

Also, I placed the ReactLoadablePlugin at the last of the plugin array. Doesn't seem to work though. :(

**Comment by tranvansang** [comment] 2022-11-17 11:51
If so, I do not think there is any problem with the webpack plugin.

The error probably comes from backend code.

ERROR in ENOENT: no such file or directory, open '/opt/maatran/build/react-loadable.json'
Error: ENOENT: no such file or directory, open '/opt/maatran/build/react-loadable.json'

**Comment by rishu605** [comment] 2022-11-17 11:55
Okay mate @tranvansang 
Thanks a lot for assisting though.

I'll try to debug the issue. Will update here if I come to any solution.

**Comment by rishu605** [comment] 2022-11-17 17:02
Hey @tranvansang,

I think I caught the issue.

When I have the following inside the callback function and the "build" folder is not already created in my project directory, then it throws that error:
```
await fsPromises.writeFile(path.join(process.cwd(), 'build/react-loadable.json'), JSON.stringify(manifest, null, 2))
```

ERROR:
```
ERROR in ENOENT: no such file or directory, open '/opt/maatran/build/react-loadable.json'
Error: ENOENT: no such file or directory, open '/opt/maatran/build/react-loadable.json'
```

BUT

when the build folder is already present in the directory, then it works perfectly fine and build succeeds with no errors.

I'm guessing this may be attributed to the way this plugin is handling folder creation. It expects the "build" folder to already exist, then only manifest object is getting stored in "react-loadable.json" file
But if build folder is not present before running this plugin, it is not able to create react-loadable.json file inside this folder.

Normally, our flow is like this -- on running ```npm run build```, we will delete our build folder completely and then webpack creates a new build folder with all the required files.

Do you think, this is some change you can add in this plugin where it does NOT expect the build folder to already be present.
It simply creates the manifest and then passes it to webpack and then webpack is responsible for creating the build folder with all its contents.

**Comment by tranvansang** [comment] 2022-11-17 18:31
Congrats on the successful debug and thanks for the feedback.

I wonder if you are using this package directly or via another wrapper service?

I think what you mean is about the sample code in readme rather than the behaviour of the plugin.
Because the plugin does not control the body of `callback`, you do define it in the webpack plugin list's declaration, right?

**Comment by rishu605** [comment] 2022-11-18 06:29
Hey,

So, I have this plugin added in webpack's plugin list. Alongwith this plugin,I am also using other plugins like DefinePlugin, WebpackAssetsManifest, WebpackPwaManifest, HashedModuleIdsPlugin, MiniCssExtractPlugin, OfflinePlugin.

Of these, WebpackAssetsManifest also saves some content inside 'build/asset-manifest.json' BUT this plugin does not expect build folder to be present beforehand to save data to this file. I think webpack handles all that folder creation.

But, when it comes to ReactLoadablePlugin, it is expecting build folder to be already present, then only it creates react-loadable.json file inside the directory.

I tested following code (inside callback), once without build folder already present, once already present. That error popped when the build directory was absent. But when I created the build folder manually in my project, ReactLoadablePlugin was able to recognize that and created react-loadable.json file inside that build directory.
```
await fsPromises.writeFile(path.join(process.cwd(), 'build/react-loadable.json'), JSON.stringify(manifest, null, 2))
```

I'm not sure if this has something to do with how plugin behaves or maybe something completely different is the issue. Still checking on that!

**Comment by tranvansang** [comment] 2022-11-18 06:35
I see. Then how about trying this

your current code:

```javascript
import { ReactLoadablePlugin } from '@react-loadable/revised/webpack';
const fs = require('fs')
const fsPromises = fs.promises

const plugins = [
  // some plugins here
  new ReactLoadablePlugin({
    async callback(manifest) {
      await fsPromises.writeFile(
        path.resolve(process.cwd(), 'build/react-loadable.json'),
        JSON.stringify(manifest, null, 2),
        {
          encoding: "utf8",
          flag: "w+"
        }
      )
    },
    absPath: true
  }),
// some other plugins here
]
```

my suggestion:

```javascript
import { ReactLoadablePlugin } from '@react-loadable/revised/webpack';
const fs = require('fs')
const fsPromises = fs.promises

const plugins = [
  // some plugins here
  new ReactLoadablePlugin({
    async callback(manifest) {
      // the following line is added
      if (!fs.existsSync(path.resolve(process.cwd(), 'build'))) fs.mkdirSync(path.resolve(process.cwd(), 'build'))
      await fsPromises.writeFile(
        path.resolve(process.cwd(), 'build/react-loadable.json'),
        JSON.stringify(manifest, null, 2),
        {
          encoding: "utf8",
          flag: "w+"
        }
      )
    },
    absPath: true
  }),
// some other plugins here
]
```

ref: https://stackoverflow.com/questions/21194934/how-to-create-a-directory-if-it-doesnt-exist-using-node-js

**Comment by rishu605** [comment] 2022-11-18 07:39
Woah, Thanks a lot.

This worked and now the build does not fail with the above error.

**Closed as completed** 2022-11-18 07:46 UTC
